# Generated by Django 2.2.5 on 2020-05-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200510_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
