# Generated by Django 2.2.5 on 2020-05-19 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200520_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersdata',
            name='password',
        ),
    ]
