# Generated by Django 2.2.5 on 2020-05-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_usersdata_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='vikcoin',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
