# Generated by Django 2.2.5 on 2020-05-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theblockchain',
            name='previoushash',
            field=models.CharField(default='0', max_length=100000),
        ),
    ]
