# Generated by Django 2.2.5 on 2020-05-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_theblockchain_previoushash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thechain', models.CharField(max_length=10000000)),
                ('index', models.IntegerField(default=0)),
                ('timestamp', models.CharField(default='-', max_length=40)),
                ('nonce', models.IntegerField(default=1)),
                ('previoushash', models.CharField(default=0, max_length=1000000)),
                ('sendername', models.CharField(default='-', max_length=1000000)),
            ],
        ),
        migrations.DeleteModel(
            name='TheBlockchain',
        ),
    ]
