# Generated by Django 2.2.5 on 2020-05-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_auto_20200522_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thelongestchain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longestchain', models.CharField(max_length=10000000)),
            ],
        ),
    ]
