# Generated by Django 2.2.5 on 2020-05-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactiondata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionid', models.IntegerField()),
                ('sendername', models.TextField(max_length=30)),
                ('recievername', models.TextField(max_length=30)),
                ('coin', models.IntegerField(max_length=30)),
                ('ipaddress', models.TextField(max_length=30)),
                ('timeanddate', models.TextField(max_length=30)),
            ],
        ),
    ]
