# Generated by Django 2.2.5 on 2020-05-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytransactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondata',
            name='coin',
            field=models.IntegerField(),
        ),
    ]
