# Generated by Django 2.2.5 on 2020-05-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytransactions', '0002_auto_20200521_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondata',
            name='transferamount',
            field=models.IntegerField(default=0),
        ),
    ]
