# Generated by Django 2.2.5 on 2020-05-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200510_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thetime',
            field=models.CharField(default='Pre-historic', max_length=12),
        ),
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.CharField(default='', max_length=40),
        ),
    ]
