# Generated by Django 2.2.5 on 2020-05-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mainsub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='Name',
            field=models.CharField(max_length=30),
        ),
    ]
