# Generated by Django 2.2.5 on 2020-05-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200509_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='vikas',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
