# Generated by Django 2.2.5 on 2020-05-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_main_vikas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='vikas',
            field=models.TextField(default='-'),
        ),
    ]
