# Generated by Django 2.2.5 on 2020-05-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200509_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='tag',
            field=models.TextField(default='-', max_length=200),
        ),
    ]
